basePath: /api/v1
definitions:
  gin_service.httpResponse:
    properties:
      response:
        type: string
    type: object
  models.Comment:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a Gin-Gonic API with gRPC integration.
  title: Gin-Gonic API with gRPC
  version: "1.0"
paths:
  /comment:
    post:
      consumes:
      - application/json
      description: 新增留言
      parameters:
      - description: Create comment
        in: body
        name: comment
        required: true
        schema:
          $ref: '#/definitions/models.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
      summary: 新增留言
      tags:
      - 留言
  /comment/{id}:
    delete:
      consumes:
      - application/json
      description: 刪除留言
      parameters:
      - description: comment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
      summary: 刪除留言
      tags:
      - 留言
    get:
      consumes:
      - application/json
      description: 獲取留言
      parameters:
      - description: comment ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
      summary: 獲取留言
      tags:
      - 留言
    put:
      consumes:
      - application/json
      description: 更新留言
      parameters:
      - description: comment ID
        in: path
        name: id
        required: true
        type: string
      - description: Update message
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/models.Comment'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
      summary: 更新留言
      tags:
      - 留言
  /comments/:
    get:
      consumes:
      - application/json
      description: 列出所有留言
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_service.httpResponse'
      summary: 列出所有留言
      tags:
      - 留言
swagger: "2.0"
